### ISSUE TITLE
Subscriber view disappears after publisher stream has been received on Android 8.0-8.1

### ISSUE THREAD

**Issue by ddimkovikj** [DreamTeamMobile/Xamarin.Opentok.Samples#2]
Test environment: Latest Xamarin.Opentok.Samples [repo](https://github.com/DreamTeamMobile/Xamarin.Opentok.Samples)

Reproduction steps:
1. Download/Clone latest Xamarin.Opentok.Samples repo
2. Create new session with default parameters on OpenTok Playground(don't publish stream yet)
3. Enter Session info credentials in OpentokTestConstants
4. Run application and join room
    At this point the publisher view is not subscriber [this](https://pasteboard.co/HtzBmG6.png) on screen.
5. Publish stream from Playground session
    At this point the subscriber view [disappears](https://pasteboard.co/HtzCedc.png) completely after publisher stream from Playground session has been received

Expected behavior: Both views should be visible after publisher stream from Playground session has been received.
Actual behavior: Subscriber view(device) disappears after publisher stream from Playground session has been received.

Important: 
The subscriber stream from device is being sent to server, but it is not being shown on screen.
Cannot be reproduced on Android versions prior to 8.0.

Device [log ](https://pastebin.com/EFYfPe0Z)

**Comment by sbokatuk** [comment]
fixed, issue was in overriding of local video container with other party video container
