### ISSUE TITLE
Event listener for getStats()

### ISSUE THREAD

**Issue by cucumbra** [DreamTeamMobile/Xamarin.Opentok.Samples#3]
Hi, I am using version 2.14.0 for android and 2.10.0 for iOS.

Is there any way I can attach event listener for the publisher so I can check the quality of the connection like package received, lost and video frame rate?

Thanks

**Comment by alexsorokoletov** [comment]
@cucumbra 2.10 for iOS is kind of old version. Let me get the info for you. Not sure though we can get the lost packages info.

**Comment by cucumbra** [comment]
@alexsorokoletov Thank you very much for the fast response. I am actually trying to implement a test call before making the actual call, so if that data is present I can compare it and decide if the call should be made.

**Comment by alexsorokoletov** [comment]
@cucumbra subscriber (`OTSubscriberKitNetworkStatsDelegate`) has two events - `VideoNetworkStatsUpdated` and `AudioNetworkStatsUpdated` should have all you need. Original iOS SDK documentation https://tokbox.com/developer/sdks/ios/reference/Classes/OTSubscriberKit.html#//api/name/networkStatsDelegate

**Comment by cucumbra** [comment]
Sorry for the late reply, we changed the requirements and we did not went that way. Thanks for the response!
