### ISSUE TITLE
Multi party?

### ISSUE THREAD

**Issue by PeraDev7** [DreamTeamMobile/Xamarin.Opentok.Samples#6]
Can i use with multiparty?

**Comment by kkarasevich** [comment]
Sure. Here is a native example provided by OpenTok
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Simple-Multiparty

**Comment by PeraDev7** [comment]
how can i integrate with the c#?

**Comment by kkarasevich** [comment]
You have to improve OpenTokStreamingService for each platform. It must support work with several input stream views. Use OpenTokSession.StreamReceived event for getting input streams like in the example of a native app I sent you above.

**Comment by PeraDev7** [comment]
I need to android only, any chances? I can't do it... can you help me?

**Comment by kkarasevich** [comment]
Contact us contact@dreamteam-mobile.com with any questions about implementing any feature you want. This project is a simple example of how you can use OpenTok for getting simple one-on-one call application.
